apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: saas-connector
spec:
  ingressClassName: traefik
  rules:
    - host: saas-connector.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000
