"""initial schema

Revision ID: 86809d2b98dd
Revises: 
Create Date: 2026-08-15 12:38:48.602244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86809d2b98dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_channels_name'), table_name='channels')
    op.create_unique_constraint(None, 'channels', ['name'])
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_constraint(None, 'channels', type_='unique')
    op.create_index(op.f('ix_channels_name'), 'channels', ['name'], unique=True)
    op.alter_column('channels', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
